#!/usr/bin/env python3
from string import ascii_letters, digits, punctuation
from urllib.parse import quote_plus
from subprocess import check_output
from random import randint, choice
from datetime import datetime
from os import environ
from re import match
from nextcord import Intents, Client, Game, Interaction, SlashOption, Member
from nextcord.ext import commands
from gpytranslate import Translator
from aiohttp import ClientSession
from orjson import loads

activity = Game(name="pisun")
intents = Intents.default()
bot = commands.Bot(intents=intents, activity=activity)

tzs = tuple(i for i in range(-12, 13))
sizeunits = {"kb": 10**3*8, "mb": 10**6*8, "gb": 10**9*8, "tb": 10**12*8,
             "kib": 2**10*8, "mib": 2**20*8, "gib": 2**30*8, "tib": 2**40*8,
             "kbit": 10**3, "mbit": 10**6, "gbit": 10**9, "tbit": 10**12,
             "kibit": 2**10, "mibit": 2**20, "gibit": 2**30, "tibit": 2**40,
             "byte": 8, "bit": 1}

@bot.slash_command(description="flip a coin")
async def coin(ctx):
    await dfr(ctx)
    result = choice(("i cant stop winning", "oh dang it"))
    await reply(ctx, result)

@bot.slash_command(description="russian roulette roll")
async def rule(ctx):
    await dfr(ctx)
    rand = randint(0, 5)
    if rand == 5:
        result = "ALAH BABAH"
    else:
        result = "you are lucky"
    await reply(ctx, result)

@bot.slash_command(description="pick a random item of specified ones")
async def pick(ctx, items: str):
    await dfr(ctx)
    result = choice(items.split())
    await reply(ctx, result)

@bot.slash_command(
    description="teams all 4* 0MR (50% EB) and all 1* 5MR (2% EB), ebi"
)
async def park(ctx, target_points):
    await dfr(ctx)
    order = check_output(("/usr/bin/python3", "./spc", "-p", target_points))
    result = str(order, "utf-8")
    await reply(ctx, result)

@bot.slash_command(description="get sekai leaderboard")
async def leaderboard(
    ctx: Interaction,
    page: int = SlashOption(choices=(1, 2, 3, 4 ,5), description="page = 25 tiers"),
    region: str = SlashOption(choices=("en", "kr", "jp", "tw", "cn")),
    wl: bool = SlashOption(choices=(True, False)),
):
    await dfr(ctx)
    if wl:
        type = "live_latest_chapter"
    else:
        type = "live"
    url = f"https://api.sekai.best/event/{type}?region={region}"
    if page == 1:
        n = slice(0, 25)
    elif page == 2:
        n = slice(25, 50)
    elif page == 3:
        n = slice(50, 75)
    elif page == 4:
        n = slice(75, 100)
    elif page == 5:
        n = slice(100, None)
    raw = await sget(url)
    json = loads(raw)
    if json["status"] == "success":
        data = json["data"]["eventRankings"]
        if data:
            board = (tier(data[i]["rank"], data[i]["userName"], data[i]["score"])
                     for i in range(len(data)))
            leaderboard = tuple(sorted(board, key=lambda x: x.top))
            result = "```\n" + "".join(f"{i}" for i in leaderboard[n]) + "```"
        else:
            result = "sekai.best prikazal umeret"
    elif json["message"] == "only world bloom event has chapter rankings":
        result = "0_o  GODDAMN THERE IS NO WL HERE"
    else:
        result = "sekai.best prikazal umeret"
    await reply(ctx, result)

@bot.slash_command(description="check is api.sekai.best alive")
async def api_check(ctx):
    await dfr(ctx)
    url = "https://api.sekai.best/status"
    statusurl = "https://status.sekai.best/history/api"
    raw = sget(url)
    if raw is None:
        result = f"[api.sekai.best]({statusurl}) umer :("
    else:
        result = f"[api.sekai.best]({statusurl}) is alive ^^"
    await reply(ctx, result)

@bot.slash_command(description="send random line of anti anti you")
async def antiyou(ctx):
    await dfr(ctx)
    line = check_output(("/usr/bin/python3", "./randomantiyou"))
    result = str(line, "utf-8")
    await reply(ctx, result)

@bot.slash_command(description="get a value for compare isvs")
async def isv(ctx, leader_skill: int, team_skill: int):
    await dfr(ctx)
    result = leader_skill*4 + team_skill - 90
    await reply(ctx, result)

@bot.slash_command(description="smert v nishite")
async def call(ctx, id: int=0):
    await dfr(ctx)
    maxurl = ("https://raw.githubusercontent.com/nedorazrab0/smert-v-nishite"
              "/main/max")
    max = int(await sget(maxurl))
    if id == 0:
        id = randint(1, max)
    elif 1 <= id <= max:
        pass
    else:
        id = 69
    result = ("https://raw.githubusercontent.com/nedorazrab0/smert-v-nishite"
                  f"/main/images/{id}.webp")
    await reply(ctx, result)

@bot.slash_command(description="change room code, invalid one = close room")
async def rm(ctx, code):
    await dfr(ctx)
    ch = ctx.channel
    regex = ".[0-9].*-[0-9|x]{5}$"
    if match(regex, ch.name):
        matchname = match(".[0-9].*-", ch.name)
        rmname = matchname[0]
        new_name = rmname + code
        if match(regex, new_name):
            await ch.edit(name=new_name)
            result = f"room code changed to {code}, lets go gambling"
        else:
            new_name = rmname + "xxxxx"
            await ch.edit(name=new_name)
            result = "room closed, " + code
    else:
        result = "the channel name must be like this shurik22-12345"
    await reply(ctx, result)

@bot.slash_command(description="convert UTC to timestamp")
async def timestamp(
    ctx: Interaction,
    year: int,
    month: int,
    day: int,
    hour: int,
    minute: int,
    type: str = SlashOption(choices={"t time short": "t", "T time long": "T",
                                     "d date short": "d", "D date long": "D",
                                     "f D+t": "f", "F very long": "F",
                                     "R timeleft": "R"})
):
    await dfr(ctx)
    date = datetime(year, month, day, hour, minute, 0)
    timestamp = int(date.timestamp())
    result = f"<t:{timestamp}:{type}>"
    await reply(ctx, result)

@bot.slash_command(description="convert timezone")
async def timezone(
    ctx: Interaction,
    hour: int,
    source_zone: int = SlashOption(choices=tzs),
    target_zone: int = SlashOption(choices=tzs)
):
    await dfr(ctx)
    converted = hour + source_zone + target_zone
    if converted > 24:
        result = f"{converted - 24} of the next day"
    elif converted < 0:
        result = f"{converted + 24} of the previous day"
    else:
        result = f"{converted} of the same day"
    await reply(ctx, result)

@bot.slash_command(description="convert rgb to hex")
async def hex(ctx, red: int, green: int, blue: int):
    await dfr(ctx)
    result = "#{:02x}{:02x}{:02x}".format(red, green, blue)
    await reply(ctx, result)

@bot.slash_command(description="convert hex to r g b  #33ccbb")
async def rgb(ctx, hex: str):
    await dfr(ctx)
    hex = hex.lstrip("#")
    if match(r"^[0-9a-fA-F]+$", hex):
        r = int(hex[0:2], 16)
        g = int(hex[2:4], 16)
        b = int(hex[4:6], 16)
        result = f"{r} {g} {b}"
    else:
        result = "ti dibil?"
    await reply(ctx, result)

@bot.slash_command(description="convert sizeunits")
async def sizeconvert(
    ctx: Interaction,
    size: int,
    sizeunit1: int = SlashOption(choices=sizeunits),
    sizeunit2: int = SlashOption(choices=sizeunits)
):
    await dfr(ctx)
    converted = (size*sizeunit1)/sizeunit2
    result = round(converted, 1)
    await reply(ctx, result)

@bot.slash_command(description="get the lenght of text")
async def ln(ctx, text):
    await dfr(ctx)
    result = len(text)
    await reply(ctx, result)

@bot.slash_command(description="translate the text")
async def tra(ctx, text: str, lang: str):
    await dfr(ctx)
    result = await translate(text, lang)
    await reply(ctx, result)

@bot.slash_command(description="translate the text into russian")
async def russian(ctx: Interaction, text_for_translation: str):
    await dfr(ctx)
    result = await translate(text_for_translation, "ru")
    await reply(ctx, result)

@bot.slash_command(description="send an extract of random wiki page")
async def wiki(ctx):
    await dfr(ctx)
    wikiurl = "https://en.wikipedia.org/w/"
    sekaipediaurl = "https://www.sekaipedia.org/w/"
    opts = ("api.php?format=json&action=query&explaintext&generator=random"
            "&grnnamespace=0&prop=extracts&grnlimit=1&exintro&redirects=")
    rand = randint(0, 2)
    if rand == 2:
        url = sekaipediaurl + opts + "/en"
    else:
        url = wikiurl + opts
    page = await sget(url)
    json = loads(page)
    id = str(*json["query"]["pages"])
    text = json["query"]["pages"][id]["extract"]
    result = await translate(text, "ru")
    if result is None:
        result = "sekai issue"
    await reply(ctx, result)

@bot.slash_command(description="calculator")
async def calculate(ctx, expr):
    await dfr(ctx)
    if match('[a-zA-Z]', expr):
        result = "do not use any letters"
    else:
        result = eval(expr.upper())
    await reply(ctx, result)

@bot.slash_command(description="get the weather in specified location")
async def weather(ctx, location):
    await dfr(ctx)
    url = f"https://wttr.in/{location}?format=%t+%C+%uuw+%T&m&lang=ru"
    result = await sget(url)
    await reply(ctx, result)

@bot.slash_command(description="repeat the text n times")
async def repeat(ctx, repeats: int, text: str):
    await dfr(ctx)
    if repeats > 2000:
        result = "too many repeats"
    else:
        text = "".join(text for i in range(int(repeats)))
        result = text[:2000]
    await reply(ctx, result)

@bot.slash_command(description="send a random string")
async def random_str(ctx):
    await dfr(ctx)
    rand = "".join(choice(ascii_letters + digits + punctuation)
                   for i in range(20))
    result = "```\n" + rand + "\n```"
    await reply(ctx, result)

@bot.slash_command(description="send a random num")
async def random(ctx, start: int=1, stop: int=100):
    await dfr(ctx)
    result = randint(start, stop)
    await reply(ctx, result)

@bot.slash_command(description="send a random prive emoji")
async def prive(ctx):
    await dfr(ctx)
    emojis = ("<a:priveKanade:1435239192857673728>",
              "<a:priveEmu:1435237988614537369>",
              "<a:priveMinoriB:1435236915342479421>",
              "<a:priveSakiD:1435234929356177428>",
              "<a:priveSakiC:1435233481730031838>",
              "<a:priveHaruka:1435232297472360478>",
              "<a:priveEmuNeneB:1435231679345328148>",
              "<a:priveEmuNeneA:1435230086554062940>",
              "<a:priveKohane:1435228559580069948>",
              "<a:priveQ84:1435226789067751544>",
              "<a:priveSakiB:1435225668676882582>",
              "<a:priveVanity:1435224819590496277>",
              "<a:priveN00b:1435221909783449702>",
              "<a:priveShizuAiri:1435220775866204210>",
              "<a:priveSakiA:1435219922753159340>",
              "<a:priveAiri:1435219009933934682>",
              "<a:priveMiku:1435217089064468582>",
              "<a:priveMinoriA:1435216177629630504>")
    result = choice(emojis)
    await reply(ctx, result)

@bot.slash_command(description="kanadewave pic")
async def kanawave(ctx):
    await dfr(ctx)
    result = "<a:kanawave:1435247126811775057>"
    await reply(ctx, result)

@bot.slash_command(description="haruka pic")
async def haru(ctx):
    await dfr(ctx)
    result = "<:haruka:1430084537676726415>"
    await reply(ctx, result)

@bot.slash_command(description="jason pic")
async def jason(ctx):
    await dfr(ctx)
    result = "<:jason:1410289021263020144>"
    await reply(ctx, result)

@bot.slash_command(description="taph pic")
async def taph(ctx):
    await dfr(ctx)
    result = "<:taph:1410288947619303484>"
    await reply(ctx, result)

@bot.slash_command(description="saki pic")
async def saki(ctx):
    await dfr(ctx)
    result = "<:saki:1410288878828388412>"
    await reply(ctx, result)

@bot.slash_command(description="teehee pic")
async def teehee(ctx):
    await dfr(ctx)
    result = "<:teehee:1410288750742995078>"
    await reply(ctx, result)

@bot.slash_command(description="patpat pic")
async def patpat(ctx):
    await dfr(ctx)
    result = "<a:patpat:1410053978921762867>"
    await reply(ctx, result)

@bot.slash_command(description="kanade pic")
async def kana(ctx):
    await dfr(ctx)
    result = "<a:kanade:1410053899859267645>"
    await reply(ctx, result)

@bot.slash_command(description="an pic")
async def an(ctx):
    await dfr(ctx)
    result = "<a:an:1410053927759646810>"
    await reply(ctx, result)

@bot.slash_command(description="white pic")
async def white(ctx):
    await dfr(ctx)
    result = "<a:white:1410053954494267485>"
    await reply(ctx, result)

@bot.slash_command(description="generate a qr code from text, 643 characters max")
async def qr(ctx, text):
    await dfr(ctx)
    url = ("https://api.qrserver.com/v1/create-qr-code/?size=999x999"
           "&qzone=4&data=" + quote_plus(text[:643], safe=""))
    result = url[:2000]
    await reply(ctx, result)

@bot.slash_command(description="hug a user <3")
async def hug(ctx, user: Member):
    await dfr(ctx)
    url = "https://nekos.life/api/v2/img/hug"
    raw = await sget(url)
    json = loads(raw)
    result = f"{user.mention}[))))]({json['url']})  <3"
    await reply(ctx, result)

@bot.slash_command(description="send a random safebooru img")
async def img(ctx):
    await dfr(ctx)
    url = ("https://safebooru.org/index.php?page=dapi&s=post&q=index&json=1"
           "&limit=1&random=true")
    raw = await sget(url)
    json = loads(raw)
    file_url = json[0]["file_url"]
    result = file_url.lstrip("\\")
    await reply(ctx, result)

@bot.slash_command(description="check is bot alive")
async def bot_check(ctx):
    await dfr(ctx)
    result = "slava ReBRT"
    await reply(ctx, result)

async def reply(ctx, result):
    """Send the result."""
    await ctx.followup.send(result)

async def dfr(ctx):
    """Do not interrupt command after 3 seconds."""
    await ctx.response.defer()

class tier:
    """Leaderboard unit."""
    def __init__(self, top, name, score):
        self.top = top
        self.name = name
        self.score = score

    def __str__(self):
        return (f"{self.top} '{self.name[slice(20)]}'"
                f" {'{0:,}'.format(self.score)}\n")

async def sget(url):
    headers = ({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
                " AppleWebKit/537.36 (KHTML, like Gecko)"
                " Chrome/100.0.4896.127 Safari/537.36"})
    async with ClientSession() as s:
        async with s.get(url, headers=headers) as resp:
            return await resp.text()

async def translate(text, lang):
    t = Translator()
    result = await t.translate(text[:690], targetlang=lang)
    return result

bot.run(environ["TOKEN"])
