#!/usr/bin/env python3
#
# Random line from antiyou

from random import choice

def random_antiyou():
    antiantiyou=("yume kibou wa shoumi kigen ga aru no yo",
                 "mada motten no? yameta hou ga... (Giveup Giveup)",
                 "kazamuki wa itsudemo magyaku",
                 "otona ni naru tte nani?",
                 "zettai aitsu nanka ni kusshinaide",
                 "anchi anchi yuu!",
                 "korogatte tsuyogatte madamada makenaide",
                 "bokura dake no enberoopu de",
                 "anchi anchi yuu!",
                 "ichidokiri no boku wa kono sekai no shujinkou",
                 "rurararura rururararura",
                 "marude jinsei rabaa",
                 "toriaezu Clap",
                 "rurararura rururararura",
                 "marude jinsei rabaa",
                 "toriaezu Clap",
                 "yume, kibou wa shoumi kigen ga aru no yo",
                 "kocchi ni oide suwatte na (Shutup Shutup)",
                 "panorama ga boku no Under",
                 "kokoro no uragawa no kagi o aketa",
                 "manma miiya manma miiya",
                 "yama ga attara tani mo an da wa",
                 "dattara More and More",
                 "atama no naka no sekaiju o",
                 "karashitakute irareru hazu wa nai kara",
                 "kitto boku wa boku no mama toberu",
                 "janpin janpin Do!",
                 "funjatte rinkaiten madamada yaresou ne",
                 "koi o shinjiru no kokoro de",
                 "janpin janpin Do!",
                 "dakedo mada fuan na kono sekai no shujinkou",
                 "ai mo kawarazu kewashiku mayotta",
                 "uso wa yada uso wa yada",
                 "uso wa yada uso wa yada",
                 "uso wa yada uso wa yada",
                 "uso wa yada uso wa yada",
                 "manma miiya manma miiya",
                 "yama ga attara tani mo an da wa",
                 "dattara More and More",
                 "erabu koto ni oku shiterya",
                 "kusari ni tsunagareta you nanda",
                 "karasanai karasanai",
                 "aitsu no iu boku nante",
                 "anchi anchi yuu!",
                 "baka datta aokatta nante iwanai iitakunai",
                 "te o tataite jiyuu da ze",
                 "anchi anchi yuu!",
                 "gouman dakedo ii ka natte",
                 "iya tte ii na yo nande",
                 "zettai aitsu nanka ni kusshinaide",
                 "anchi anchi yuu!",
                 "korogatte tsuyogatte madamada makenaide",
                 "bokura dake no enberoopu de",
                 "anchi anchi yuu!",
                 "kimi datte ubawaretakunai desho",
                 "boku wa boku no mama toberu",
                 "janpin janpin Do!",
                 "funjatte rinkaiten madamada yaresou ne",
                 "koi o shinjiru no kokoro de",
                 "janpin janpin Do!",
                 "ichidokiri no boku wa kono sekai de ichidokiri no shujinkou",
                 "rurararura rururararura",
                 "sore ga jinsei",
                 "bokura toriaezu Clap",
                 "rurararura rururararura",
                 "sore ga jinsei",
                 "bokura toriaezu Clap",
                 "rurararura rururararura")

    return choice(antiantiyou)

def main():
    print(random_antiyou())

if __name__ == "__main__":
    main()
